import React, { useState } from 'react';
import { FileText, Copy, Check, Printer, Sparkles } from 'lucide-react';
import { useToast } from './Toast';
import api from '../services/api';

export const NotesCitationTab: React.FC = () => {
  const { showToast } = useToast();
  const [bookTitle, setBookTitle] = useState('');
  const [authorName, setAuthorName] = useState('');
  const [pubYear, setPubYear] = useState(new Date().getFullYear().toString());
  const [loading, setLoading] = useState(false);
  const [notesType, setNotesType] = useState('Quick Notes');
  const [generatedNotes, setGeneratedNotes] = useState('');
  const [copiedStyle, setCopiedStyle] = useState<string | null>(null);

  // Citation styles
  const citations = {
    APA: `${authorName || 'Author'}. (${pubYear}). ${bookTitle || 'Book Title'}. Publisher.`,
    MLA: `${authorName || 'Author'}. *${bookTitle || 'Book Title'}*. Publisher, ${pubYear}.`,
    IEEE: `[1] ${authorName.charAt(0) || 'A'}. ${authorName.split(' ')[1] || 'Author'}, *${bookTitle || 'Book Title'}*, Publisher, ${pubYear}.`,
    Chicago: `${authorName || 'Author'}. ${pubYear}. *${bookTitle || 'Book Title'}*. City: Publisher.`,
    Harvard: `${authorName || 'Author'}, ${pubYear}. *${bookTitle || 'Book Title'}*, Publisher.`
  };

  const handleCopyCitation = (style: string, text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedStyle(style);
    showToast(`${style} Citation copied!`, 'success');
    setTimeout(() => setCopiedStyle(null), 2000);
  };

  const handleGenerateNotes = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!bookTitle) return;
    setLoading(true);
    try {
      const res = await api.post('/ai/chat', {
        message: `Generate structured academic ${notesType} for the book or topic "${bookTitle}" by ${authorName || 'unknown'}. Include exactly 3 bullet summaries, 2 definitions, and 2 common interview/exam questions with short answers.`
      });
      if (res.data.success) {
        setGeneratedNotes(res.data.reply);
        showToast('Study notes generated by ALPHA!', 'success');
      }
    } catch (err) {
      console.error(err);
      // Fallback
      setGeneratedNotes(`**ALPHA Study Notes Fallback on ${bookTitle}**\n\n- **Summary**: Essential overview of ${bookTitle} topics.\n- **Definition**: Core frameworks and design algorithms.\n- **Practice Q1**: How does clean architecture work? \n  *Answer*: By separation of data layers.`);
    } finally {
      setLoading(false);
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      {/* Citation Builder Column */}
      <div className="glass-card p-6 rounded-3xl space-y-6 h-fit">
        <h3 className="font-extrabold text-base text-slate-900 dark:text-white flex items-center gap-2">
          <Copy className="w-5 h-5 text-brand-600" />
          AI Citation Generator
        </h3>
        
        <div className="space-y-4">
          <div>
            <label className="block text-[10px] uppercase font-bold text-slate-450 mb-1.5">Book Title</label>
            <input
              type="text"
              value={bookTitle}
              onChange={(e) => setBookTitle(e.target.value)}
              placeholder="e.g. Effective Java"
              className="form-input text-xs"
              required
            />
          </div>

          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-[10px] uppercase font-bold text-slate-450 mb-1.5">Author</label>
              <input
                type="text"
                value={authorName}
                onChange={(e) => setAuthorName(e.target.value)}
                placeholder="Joshua Bloch"
                className="form-input text-xs"
              />
            </div>
            <div>
              <label className="block text-[10px] uppercase font-bold text-slate-455 mb-1.5">Year</label>
              <input
                type="number"
                value={pubYear}
                onChange={(e) => setPubYear(e.target.value)}
                className="form-input text-xs"
              />
            </div>
          </div>
        </div>

        {/* Citations Copy List */}
        <div className="space-y-3 pt-2">
          {Object.entries(citations).map(([style, text]) => (
            <div
              key={style}
              className="p-3 bg-slate-50 dark:bg-slate-900/60 border border-slate-205/35 dark:border-slate-850 rounded-2xl flex items-center justify-between gap-3 text-[11px]"
            >
              <div className="truncate flex-1">
                <span className="font-bold text-brand-600 block text-[9px] uppercase tracking-wider">{style} Format</span>
                <p className="text-slate-600 dark:text-slate-350 truncate italic mt-0.5">{text}</p>
              </div>
              <button
                onClick={() => handleCopyCitation(style, text)}
                className="p-2 bg-white dark:bg-slate-800 hover:bg-slate-100 border dark:border-slate-700 rounded-xl cursor-pointer"
              >
                {copiedStyle === style ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5 text-slate-400" />}
              </button>
            </div>
          ))}
        </div>
      </div>

      {/* Notes Builder Column */}
      <div className="lg:col-span-2 glass-card p-6 rounded-3xl space-y-6">
        <h3 className="font-extrabold text-base text-slate-900 dark:text-white flex items-center gap-2">
          <FileText className="w-5 h-5 text-indigo-500" />
          AI Revision Notes Generator
        </h3>

        <form onSubmit={handleGenerateNotes} className="flex flex-wrap gap-4 items-end">
          <div className="flex-1 min-w-[200px]">
            <label className="block text-[10px] uppercase font-bold text-slate-450 mb-1.5">Select Notes Format</label>
            <select
              value={notesType}
              onChange={(e) => setNotesType(e.target.value)}
              className="form-input text-xs"
            >
              <option value="Quick Notes">Quick Notes Summary</option>
              <option value="Exam Notes">Exam Prep Outlines</option>
              <option value="Interview Notes">Interview Cheat Sheet</option>
              <option value="Revision Notes">Detailed Chapter Notes</option>
            </select>
          </div>
          <button
            type="submit"
            disabled={loading || !bookTitle}
            className="btn-primary py-2.5 px-5 text-xs font-bold rounded-xl flex items-center gap-1 cursor-pointer"
          >
            <Sparkles className="w-4 h-4 animate-pulse" />
            Compile Notes
          </button>
        </form>

        {/* Generated output */}
        {generatedNotes ? (
          <div className="space-y-4">
            <div className="p-5 bg-slate-50 dark:bg-slate-950 border border-slate-205/30 rounded-2xl overflow-y-auto max-h-[22rem] scrollbar-thin">
              <pre className="text-xs text-slate-700 dark:text-slate-350 leading-relaxed font-sans whitespace-pre-wrap">
                {generatedNotes}
              </pre>
            </div>
            <div className="flex justify-end gap-2">
              <button
                onClick={handlePrint}
                className="btn-secondary py-2 px-4 text-xs font-bold rounded-xl flex items-center gap-1.5 cursor-pointer"
              >
                <Printer className="w-4 h-4" />
                Print/Export PDF
              </button>
            </div>
          </div>
        ) : (
          <div className="text-center py-12 text-slate-400 border border-dashed border-slate-200 dark:border-slate-800 rounded-3xl">
            <FileText className="w-10 h-10 mx-auto opacity-20 mb-3" />
            <h4 className="font-bold text-sm text-slate-700">No notes compiled yet</h4>
            <p className="text-xs mt-1">Enter a Book Title in the citation generator and select notes format above.</p>
          </div>
        )}
      </div>
    </div>
  );
};
